/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* hdlname = "\\counter_gen" *)
(* dynports =  1  *)
(* top =  1  *)
(* src = "../src/counter_gen.v:1.1-16.10" *)
module counter_gen(clk, rstn, out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire _08_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _09_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _10_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _11_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _12_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _13_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _14_;
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _22_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _23_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _24_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _25_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _26_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _27_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _28_;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  wire _29_;
  (* force_downto = 32'd1 *)
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [7:0] _30_;
  (* force_downto = 32'd1 *)
  (* src = "../src/counter_gen.v:13.16-13.23|/usr/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _31_;
  (* src = "../src/counter_gen.v:5.26-5.29" *)
  input clk;
  wire clk;
  (* src = "../src/counter_gen.v:7.27-7.30" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "../src/counter_gen.v:6.26-6.30" *)
  input rstn;
  wire rstn;
  sky130_fd_sc_hd__clkinv_1 _32_ (
    .A(_22_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nand2_1 _33_ (
    .A(_23_),
    .B(_22_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__xor2_1 _34_ (
    .A(_23_),
    .B(_22_),
    .X(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(_24_),
    .B(_16_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__and4_1 _36_ (
    .A(_23_),
    .B(_22_),
    .C(_24_),
    .D(_25_),
    .X(_17_)
  );
  sky130_fd_sc_hd__a31oi_1 _37_ (
    .A1(_23_),
    .A2(_22_),
    .A3(_24_),
    .B1(_25_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _38_ (
    .A(_17_),
    .B(_18_),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nand2_1 _39_ (
    .A(_26_),
    .B(_17_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__xor2_1 _40_ (
    .A(_26_),
    .B(_17_),
    .X(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_27_),
    .B(_19_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nand4_1 _42_ (
    .A(_26_),
    .B(_27_),
    .C(_28_),
    .D(_17_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__a31oi_1 _43_ (
    .A1(_26_),
    .A2(_27_),
    .A3(_17_),
    .B1(_28_),
    .Y(_21_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _44_ (
    .A(_20_),
    .SLEEP(_21_),
    .X(_14_)
  );
  sky130_fd_sc_hd__xnor2_1 _45_ (
    .A(_29_),
    .B(_20_),
    .Y(_15_)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_30_[0]),
    .Q(out[0]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_31_[1]),
    .Q(out[1]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_31_[2]),
    .Q(out[2]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_31_[3]),
    .Q(out[3]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_31_[4]),
    .Q(out[4]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_31_[5]),
    .Q(out[5]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_31_[6]),
    .Q(out[6]),
    .RESET_B(rstn)
  );
  (* src = "../src/counter_gen.v:9.4-14.7" *)
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(_31_[7]),
    .Q(out[7]),
    .RESET_B(rstn)
  );
  assign _30_[7:1] = out[7:1];
  assign _31_[0] = _30_[0];
  assign _23_ = out[1];
  assign _22_ = out[0];
  assign _31_[1] = _09_;
  assign _24_ = out[2];
  assign _31_[2] = _10_;
  assign _25_ = out[3];
  assign _31_[3] = _11_;
  assign _26_ = out[4];
  assign _31_[4] = _12_;
  assign _27_ = out[5];
  assign _31_[5] = _13_;
  assign _28_ = out[6];
  assign _31_[6] = _14_;
  assign _29_ = out[7];
  assign _31_[7] = _15_;
  assign _30_[0] = _08_;
endmodule
